language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - git clone git://github.com/json-ld/json-ld.org.git
  - mv ./json-ld.org/test-suite/tests ./Test/
  - rm -rf ./json-ld.org
  - composer install
